import { Request, Response, NextFunction } from 'express';
import { container } from 'tsyringe';
import { IPurchaseRepository } from '../../../domain/repositories/IPurchaseRepository';
import { IActivityLogRepository } from '../../../domain/repositories/IActivityLogRepository';
import { IStockRepository } from '../../../domain/repositories/IWarehouseRepository';
import { IOrdenPagoRepository } from '../../../domain/repositories/IOrdenPagoRepository';
import { NotFoundError, AppError } from '../../../shared/errors/AppError';
import prisma from '../../database/prisma';
import { recordPurchaseCreated } from '../../services/AccountingService';

export class PurchaseController {
  async findAll(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const repo = container.resolve<IPurchaseRepository>('PurchaseRepository');
      const { page, limit, supplierId, status, dateFrom, dateTo } = req.query;

      const result = await repo.findAll(
        { page: Number(page) || 1, limit: Number(limit) || 20 },
        {
          supplierId: supplierId as string | undefined,
          status: status as 'REGISTERED' | 'CANCELLED' | undefined,
          companyId: req.companyId,
          fiscalMode: req.fiscalMode,
          dateFrom: dateFrom ? new Date(dateFrom as string) : undefined,
          dateTo: dateTo ? new Date(dateTo as string) : undefined,
        }
      );

      res.json({ status: 'success', ...result });
    } catch (error) {
      next(error);
    }
  }

  async findById(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const repo = container.resolve<IPurchaseRepository>('PurchaseRepository');
      const purchase = await repo.findById(req.params.id);
      if (!purchase) throw new NotFoundError('Purchase');
      res.json({ status: 'success', data: purchase });
    } catch (error) {
      next(error);
    }
  }

  async create(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const repo = container.resolve<IPurchaseRepository>('PurchaseRepository');
      const activityLogRepo = container.resolve<IActivityLogRepository>('ActivityLogRepository');
      const stockRepo = container.resolve<IStockRepository>('StockRepository');

      const saleCondition: string = req.body.saleCondition ?? 'CONTADO';

      // Document type (Factura / Nota de Crédito / Nota de Débito)
      const ALLOWED_TYPES = [
        'FACTURA_A', 'FACTURA_B', 'FACTURA_C',
        'NOTA_CREDITO_A', 'NOTA_CREDITO_B', 'NOTA_CREDITO_C',
        'NOTA_DEBITO_A', 'NOTA_DEBITO_B', 'NOTA_DEBITO_C',
      ];
      const type: string = ALLOWED_TYPES.includes(req.body.type) ? req.body.type : 'FACTURA_A';
      const isNC = type.startsWith('NOTA_CREDITO');
      const isND = type.startsWith('NOTA_DEBITO');
      const docLabel = isNC ? 'Nota de Crédito' : isND ? 'Nota de Débito' : 'Compra';

      // Auto-generate number with a prefix per document kind
      const year = new Date().getFullYear();
      const prefix = isNC ? 'NCC' : isND ? 'NDC' : 'COMP';
      const count = await prisma.$queryRaw<{ c: bigint }[]>`
        SELECT COUNT(*) AS c FROM "purchases"
        WHERE "companyId" = ${req.companyId} AND number LIKE ${prefix + '-' + year + '-%'}
      `;
      const autoNumber = `${prefix}-${year}-${String(Number((count[0]?.c ?? 0n)) + 1).padStart(4, '0')}`;

      const purchase = await repo.create({
        type: type as any,
        number: autoNumber,
        supplierId: req.body.supplierId,
        userId: req.user!.userId,
        companyId: req.companyId,
        warehouseId: req.body.warehouseId || undefined,
        date: req.body.date ? new Date(req.body.date) : undefined,
        currency: req.body.currency,
        notes: req.body.notes,
        items: req.body.items,
      });

      // Persist saleCondition + fiscalMode + originPurchaseId + exchangeRate via raw SQL (stale Prisma client workaround)
      const fiscalMode = req.fiscalMode ?? 'FORMAL';
      const originPurchaseId: string | null = (isNC || isND) ? (req.body.originPurchaseId ?? null) : null;
      const exchangeRate = Number(req.body.exchangeRate) > 0 ? Number(req.body.exchangeRate) : 1;
      await prisma.$executeRaw`
        UPDATE "purchases"
        SET "saleCondition" = ${saleCondition}, "fiscalMode" = ${fiscalMode},
            "originPurchaseId" = ${originPurchaseId}, "exchangeRate" = ${exchangeRate}
        WHERE id = ${purchase.id}
      `;

      // NOTE: the supplier current-account debt is now generated by the purchase
      // INVOICE (see PurchaseInvoiceController + syncPurchaseInvoiceMovements),
      // not by the purchase. A purchase only moves stock.

      // Auto-stock: FC adds stock (PURCHASE); NC returns it to supplier
      // (ADJUSTMENT_OUT); ND is a financial adjustment with no goods movement.
      if (purchase.warehouseId && !isND) {
        const stockType: 'PURCHASE' | 'ADJUSTMENT_OUT' = isNC ? 'ADJUSTMENT_OUT' : 'PURCHASE';
        const itemsWithProduct = purchase.items.filter((i) => i.productId);
        for (const item of itemsWithProduct) {
          try {
            await stockRepo.addMovement({
              productId: item.productId!,
              variantId: (item as any).variantId ?? null,
              warehouseId: purchase.warehouseId,
              type: stockType,
              quantity: Number(item.quantity),
              reason: `${docLabel} ${purchase.number}`,
              referenceId: purchase.id,
              userId: req.user!.userId,
            });
          } catch (stockError) {
            // Log stock error but don't fail the purchase creation
            console.error(`Stock movement failed for product ${item.productId}:`, stockError);
          }
        }
      }

      await activityLogRepo.create({
        userId: req.user!.userId,
        action: 'CREATE',
        entity: 'Purchase',
        entityId: purchase.id,
        description: `Compra ${purchase.number} registrada`,
      });

      // Auto-generate journal entry (only for Facturas — NC/ND would need
      // reversed entries which are not modelled here yet)
      if (!isNC && !isND) {
        await recordPurchaseCreated({
          id: purchase.id,
          number: purchase.number,
          subtotal: Number(purchase.subtotal),
          taxAmount: Number(purchase.taxAmount),
          total: Number(purchase.total),
          companyId: req.companyId!,
          userId: req.user!.userId,
        });
      }

      res.status(201).json({ status: 'success', data: purchase });
    } catch (error) {
      next(error);
    }
  }

  async getPendingInvoices(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { supplierId } = req.query;
      if (!supplierId) throw new AppError('supplierId es requerido', 400);

      // Invoices are now standalone (their own supplierId/currency). Query them
      // directly; the linked purchase is optional/legacy.
      const rows = await prisma.$queryRaw<{
        id: string; number: string; type: string; amount: any; subtotal: any;
        taxRate: any; taxAmount: any; dueDate: Date | null; paymentMethod: string;
        purchaseId: string | null; purchaseNumber: string | null; purchaseDate: Date | null; currency: string;
      }[]>`
        SELECT pi.id, pi.number, pi.type, pi.amount, pi.subtotal, pi."taxRate", pi."taxAmount",
               pi."dueDate", pi."paymentMethod", pi.currency,
               p.id AS "purchaseId", p.number AS "purchaseNumber", p.date AS "purchaseDate"
        FROM "purchase_invoices" pi
        LEFT JOIN "purchases" p ON p.id = pi."purchaseId"
        WHERE pi."supplierId" = ${supplierId as string}
          AND pi."companyId" = ${req.companyId}
          AND pi.status = 'PENDING'
        ORDER BY pi."createdAt" ASC
      `;

      res.json({ status: 'success', data: rows });
    } catch (error) {
      next(error);
    }
  }

  async assignWarehouse(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const repo      = container.resolve<IPurchaseRepository>('PurchaseRepository');
      const stockRepo = container.resolve<IStockRepository>('StockRepository');

      const purchase = await repo.findById(req.params.id);
      if (!purchase) throw new NotFoundError('Purchase');
      if (purchase.warehouseId) throw new AppError('Esta compra ya tiene un almacén asignado', 400);

      const { warehouseId } = req.body;
      if (!warehouseId) throw new AppError('warehouseId es requerido', 400);

      const updated = await repo.update(req.params.id, { warehouseId });

      // Stock movements depend on document kind: FC adds, NC returns, ND none
      const pType = String((purchase as any).type ?? 'FACTURA_A');
      const pIsNC = pType.startsWith('NOTA_CREDITO');
      const pIsND = pType.startsWith('NOTA_DEBITO');
      if (!pIsND) {
        const stockType: 'PURCHASE' | 'ADJUSTMENT_OUT' = pIsNC ? 'ADJUSTMENT_OUT' : 'PURCHASE';
        const itemsWithProduct = purchase.items.filter((i) => i.productId);
        for (const item of itemsWithProduct) {
          try {
            await stockRepo.addMovement({
              productId: item.productId!,
              warehouseId,
              type: stockType,
              quantity: Number(item.quantity),
              reason: `${pType} ${purchase.number} (almacén asignado)`,
              referenceId: purchase.id,
              userId: req.user!.userId,
            });
          } catch (stockError) {
            console.error(`Stock movement failed for product ${item.productId}:`, stockError);
          }
        }
      }

      res.json({ status: 'success', data: updated });
    } catch (error) {
      next(error);
    }
  }

  async cancel(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const repo = container.resolve<IPurchaseRepository>('PurchaseRepository');
      const activityLogRepo = container.resolve<IActivityLogRepository>('ActivityLogRepository');

      const purchase = await repo.findById(req.params.id);
      if (!purchase) throw new NotFoundError('Purchase');

      if (purchase.status === 'CANCELLED') {
        throw new AppError('La compra ya está cancelada', 400);
      }

      const updated = await repo.update(req.params.id, { status: 'CANCELLED' });

      // Reverse any supplier account movement generated by this purchase / NC / ND
      const opRepo = container.resolve<IOrdenPagoRepository>('OrdenPagoRepository');
      await opRepo.reverseSupplierMovementByPurchase(purchase.id);

      await activityLogRepo.create({
        userId: req.user!.userId,
        action: 'CANCEL',
        entity: 'Purchase',
        entityId: purchase.id,
        description: `Compra ${purchase.number} cancelada`,
      });

      res.json({ status: 'success', data: updated });
    } catch (error) {
      next(error);
    }
  }
}
