export { default as api } from './api';
export { default as authService } from './auth.service';
export { default as customersService } from './customers.service';
export { default as productsService } from './products.service';
export { default as categoriesService } from './categories.service';
export { default as warehousesService } from './warehouses.service';
export { default as stockService } from './stock.service';
export { default as invoicesService } from './invoices.service';
export { default as currentAccountsService } from './current-accounts.service';
export { default as remitosService } from './remitos.service';
export { default as cashRegistersService } from './cash-registers.service';
export { default as activityLogsService } from './activity-logs.service';
export { default as afipService } from './afip.service';
export { default as ivaService } from './iva.service';
export { default as suppliersService } from './suppliers.service';
export { default as purchasesService } from './purchases.service';
export { default as dashboardService } from './dashboard.service';
export type { DashboardStats } from './dashboard.service';
