ALTER TABLE "purchase_invoices"
  ADD COLUMN IF NOT EXISTS "type"          TEXT          NOT NULL DEFAULT 'FACTURA_A',
  ADD COLUMN IF NOT EXISTS "subtotal"      DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "taxRate"       DECIMAL(5,2)  NOT NULL DEFAULT 21,
  ADD COLUMN IF NOT EXISTS "taxAmount"     DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT          NOT NULL DEFAULT 'BANK_TRANSFER';
