ALTER TABLE "app_settings"
  ADD COLUMN IF NOT EXISTS "smtpHost"   TEXT,
  ADD COLUMN IF NOT EXISTS "smtpPort"   INTEGER NOT NULL DEFAULT 587,
  ADD COLUMN IF NOT EXISTS "smtpUser"   TEXT,
  ADD COLUMN IF NOT EXISTS "smtpPass"   TEXT,
  ADD COLUMN IF NOT EXISTS "smtpFrom"   TEXT,
  ADD COLUMN IF NOT EXISTS "smtpSecure" BOOLEAN NOT NULL DEFAULT false;
