-- Add FINANCES and PURCHASES roles to UserRole enum
DO $$ BEGIN
  ALTER TYPE "UserRole" ADD VALUE 'FINANCES';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "UserRole" ADD VALUE 'PURCHASES';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
